title: Umar Pirmahomed
description: Aspiring Softare Engineer and Data Scientist
site_title: '@Umarpir - Umar Pirmahomed'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: umarpir
blog_url: https://umarpir.github.io
email: Umarpir99@gmail.com.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics:
